#!/usr/local/bin/python3

def count_letters(text):
    lower=0
    upper=0
    for t in text:
        if t.islower():
            lower=lower+1
            #print("lower:" + str(lower))
        elif t.isupper():
            upper=upper+1
            #print("upper:" + str(upper))
#        else:
#            pass
    return "lower:" + str(lower) + " " +  "upper:" + str(upper) 

out=count_letters("Tutorials POINT")
print(out)
