#!/usr/local/bin/python3
"""
Input: a = 2, b = 4
Output: 4

Input: a = -1, b = -4
Output: -1
"""
def max_of_two_numbers(a,b):
    if a > b:
       return str(a) + "max"
    else:
       return str(b) + "max" 

test=max_of_two_numbers(-2,-4)
print(test)
