#!/usr/local/bin/python3
#INPUT
"""
#list = [10, 11, 12, 13, 14, 15]
list = [4, 5, 6, 7, 8, 9]
print("Starting list:" + str(list))

def reverse_list(list):
    list[0], list[1], list[2], list[3], list[4], list[5] = list[5], list[4], list[3], list[2], list[1], list[0]
    return list

#a=reverse_list([10, 11, 12, 13, 14, 15])
a=reverse_list([4, 5, 6, 7, 8, 9])
print(a)
"""

"""
SMARTER WAY
"""
list = [4, 5, 6, 7, 8, 9]
print("Starting list:" + str(list))
def reverse_list(list):
#   built in reverse function will also show a list in reverse for you.
#   list = list.reverse()
    list = list[::-1]
    return list

a=reverse_list([4, 5, 6, 7, 8, 9])
print(a)
