#!/usr/local/bin/python3
"""
Simple interest formula is given by:
Simple Interest = (P x T x R)/100
Where,
P is the principle amount
T is the time and
R is the rate
"""
def simple_interest(p,t,r):
    interest=(p * t * r)/100
    return interest
out=simple_interest(10000,5,5)
print(out)
