#!/usr/local/bin/python3
"""
Given a list of numbers, write a Python program to find the sum of all the elements in the list.
Example: 
 

Input: [12, 15, 3, 10]
Output: 40

Input: [17, 5, 3, 5]
Output: 30

"""

def sum_elements(input):
    sum=0
    for elements in input:
        sum+=elements
    return sum

#input=[12, 15, 3, 10]
input=[17, 5, 3, 5]
out=sum_elements(input)
print(out)
